name: Make and Deploy Images

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-and-deploy-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python (3.11)
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .

      - name: Run nbody.py with cpp backend
        run: export NBODY_BACKEND=cpp; python nbody.py

      - name: Run nbody.py with jax backend
        run: export NBODY_BACKEND=jax; python nbody.py

      - name: Generate index.html for image browsing
        run: python make_html.py

      - name: Copy generated images
        run: |
          mkdir deploy-images
          cp -r images deploy-images/images
          cp images/index.html deploy-images/index.html
          rm images/index.html

      - name: Push images to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./deploy-images
          force_orphan: true
          commit_message: "Deploy generated images from workflow [skip ci]"
